import { CookieInventoryItem } from '@/types/privacy';

export const OFFICIAL_COOKIE_INVENTORY: CookieInventoryItem[] = [
  {
    id: 'cookie-sess',
    name: 'gudpreiss_session_id',
    provider: 'GudPreiss (First-party)',
    purpose: 'Aufrechterhaltung der Sitzung und Speicherung des Warenkorbs',
    category: 'necessary',
    duration: 'Session',
    domain: 'gudpreiss.de',
    data_collected: 'Anonyme Sitzungs-ID',
    legal_basis: 'Art. 6 Abs. 1 lit. f DSGVO / § 25 Abs. 2 TDDDG',
    consent_required: false,
  },
  {
    id: 'cookie-consent',
    name: 'gudpreiss_dsgvo_consent',
    provider: 'GudPreiss (First-party)',
    purpose: 'Speicherung Ihrer Cookie- und Datenschutz-Einwilligungen',
    category: 'necessary',
    duration: '1 Jahr',
    domain: 'gudpreiss.de',
    data_collected: 'Einwilligungskategorien, Timestamp, Policy-Version',
    legal_basis: 'Art. 6 Abs. 1 lit. c DSGVO (Rechtliche Verpflichtung)',
    consent_required: false,
  },
  {
    id: 'cookie-theme',
    name: 'gudpreiss_theme_pref',
    provider: 'GudPreiss (First-party)',
    purpose: 'Speicherung der bevorzugten Farbdarstellung (Dark/Light Mode)',
    category: 'preferences',
    duration: '1 Jahr',
    domain: 'gudpreiss.de',
    data_collected: 'Design-Einstellung',
    legal_basis: 'Art. 6 Abs. 1 lit. a DSGVO / § 25 Abs. 1 TDDDG',
    consent_required: true,
  },
  {
    id: 'cookie-stats',
    name: 'gudpreiss_analytics_id',
    provider: 'GudPreiss (First-party Analytics)',
    purpose: 'Reichweitenmessung und statistische Analyse der Seitennutzung',
    category: 'statistics',
    duration: '6 Monate',
    domain: 'gudpreiss.de',
    data_collected: 'Pseudonyme Besucher-ID, Klicks, Verweildauer',
    legal_basis: 'Art. 6 Abs. 1 lit. a DSGVO / § 25 Abs. 1 TDDDG',
    consent_required: true,
  },
  {
    id: 'cookie-marketing',
    name: 'gudpreiss_mkt_tr',
    provider: 'GudPreiss Marketing Engine',
    purpose: 'Messung von Kampagnenerfolgen und gezielte Produktempfehlungen',
    category: 'marketing',
    duration: '30 Tage',
    domain: 'gudpreiss.de',
    data_collected: 'Interessenkategorien, Konvertierungs-ID',
    legal_basis: 'Art. 6 Abs. 1 lit. a DSGVO / § 25 Abs. 1 TDDDG',
    consent_required: true,
  },
  {
    id: 'cookie-ai',
    name: 'gudpreiss_ai_profile',
    provider: 'GudPreiss AI Assistant',
    purpose: 'KI-gestützte Beratungsanpassung und Ermittlung von Kaufabsichten',
    category: 'personalization_ai',
    duration: '7 Tage',
    domain: 'gudpreiss.de',
    data_collected: 'Interaktionsmuster im Chat, Beratungsverlauf',
    legal_basis: 'Art. 6 Abs. 1 lit. a DSGVO (Ausdrückliche Einwilligung)',
    consent_required: true,
  },
];
