import { Subprocessor, ProcessingActivity, RetentionRule } from '@/types/privacy';

export const OFFICIAL_SUBPROCESSORS: Subprocessor[] = [
  {
    id: 'sub-vercel',
    name: 'Vercel Inc.',
    service: 'Hosting & Serverless Edge Functions',
    purpose: 'Bereitstellung der Webanwendung und Ausführung von API-Endpunkten',
    data_categories: ['IP-Adresse', 'HTTP-Header', 'Sitzungsdaten'],
    processing_location: 'EU (Frankfurt, Deutschland) / USA',
    dpa_status: 'signed',
    transfer_mechanism: 'EU_US_DPF',
    risk_level: 'low',
  },
  {
    id: 'sub-supabase',
    name: 'Supabase Inc.',
    service: 'Datenbank & Authentifizierung',
    purpose: 'Sichere Speicherung von Kundenprofilen, Bestellungen und Produktdaten',
    data_categories: ['Stammdaten', 'Kontaktdaten', 'Bestellhistorie'],
    processing_location: 'EU (AWS Frankfurt, Deutschland)',
    dpa_status: 'signed',
    transfer_mechanism: 'EU_EEA',
    risk_level: 'low',
  },
  {
    id: 'sub-ai-provider',
    name: 'Google Cloud Platform (Gemini AI API)',
    service: 'KI-Sprachmodell & Konversations-Assistent',
    purpose: 'Verarbeitung von Kundenanfragen im GudPreiss Chat-Assistenten',
    data_categories: ['Chat-Eingaben', 'Anfrage-Kontext'],
    processing_location: 'EU (Google Cloud Frankfurt, Deutschland)',
    dpa_status: 'signed',
    transfer_mechanism: 'EU_EEA',
    risk_level: 'medium',
  },
  {
    id: 'sub-stripe',
    name: 'Stripe Payments Europe, Ltd.',
    service: 'Zahlungsabwicklung',
    purpose: 'Sichere Durchführung von Kreditkarten- und Online-Zahlungen',
    data_categories: ['Zahlungsdaten', 'Transaktions-ID', 'Rechnungsadresse'],
    processing_location: 'Irland (EU)',
    dpa_status: 'signed',
    transfer_mechanism: 'EU_EEA',
    risk_level: 'low',
  },
];

export const OFFICIAL_PROCESSING_ACTIVITIES: ProcessingActivity[] = [
  {
    id: 'pa-orders',
    name: 'Bestellabwicklung und Vertragserfüllung',
    controller: 'GudPreiss E-Commerce GmbH',
    purpose: 'Abwicklung von Kaufverträgen, Lieferung und Kundenservice',
    data_subject_categories: ['Kunden', 'Käufer'],
    data_categories: ['Name', 'Adresse', 'E-Mail', 'Zahlungsdaten', 'Bestellte Artikel'],
    recipient_categories: ['Zahlungsdienstleister', 'Logistikpartner (DHL/DPD)'],
    international_transfers: ['Keine'],
    retention_period: '10 Jahre gem. § 147 AO / § 257 HGB',
    security_measures: ['TLS-Verschlüsselung', 'Zugriffsbeschränkungen', 'RBAC'],
    legal_basis: 'Art. 6 Abs. 1 lit. b DSGVO (Vertragserfüllung)',
  },
  {
    id: 'pa-ai-support',
    name: 'Interaktive Kundenberatung durch GudPreiss KI-Assistent',
    controller: 'GudPreiss E-Commerce GmbH',
    purpose: 'Beantwortung von Produktfragen und Beratung im Chat',
    data_subject_categories: ['Webseitenbesucher', 'Kunden'],
    data_categories: ['Chatverlauf', 'Produktpräferenzen'],
    recipient_categories: ['Google Cloud AI'],
    international_transfers: ['EU-Rechenzentrum Frankfurt'],
    retention_period: 'Max. 30 Tage oder bis zum Widerruf',
    security_measures: ['Anonymisierung', 'Pseudonymisierung', 'Session-Isolierung'],
    legal_basis: 'Art. 6 Abs. 1 lit. a DSGVO / Art. 6 Abs. 1 lit. f DSGVO',
  },
];

export const OFFICIAL_RETENTION_RULES: RetentionRule[] = [
  {
    id: 'ret-1',
    data_type: 'Sitzungs- & Cookie-Daten',
    purpose: 'Aufrechterhaltung des Warenkorbs und Seitennavigation',
    legal_basis: 'Art. 6 Abs. 1 lit. f DSGVO / § 25 Abs. 2 TDDDG',
    retention_period: 'Dauer der Sitzung (Session-Ende)',
    storage_location: 'Lokaler Browser-Speicher',
    deletion_method: 'Automatisches Schließen des Browsers',
  },
  {
    id: 'ret-2',
    data_type: 'Bestell- & Rechnungsdaten',
    purpose: 'Erfüllung steuer- und handelsrechtlicher Aufbewahrungspflichten',
    legal_basis: 'Art. 6 Abs. 1 lit. c DSGVO i.V.m. § 147 AO / § 257 HGB',
    retention_period: '10 Jahre ab Kalenderjahresende',
    storage_location: 'GudPreiss Hauptdatenbank (Frankfurt)',
    deletion_method: 'Automatisierte Löschanforderung nach Ablauf der Frist',
  },
  {
    id: 'ret-3',
    data_type: 'Marketing- & Profiling-Einwilligungen',
    purpose: 'Nachweis der rechtmäßigen Erteilung der Einwilligung',
    legal_basis: 'Art. 6 Abs. 1 lit. c DSGVO i.V.m. Art. 7 Abs. 1 DSGVO',
    retention_period: '3 Jahre ab Widerruf (Verjährungsfrist § 195 BGB)',
    storage_location: 'GudPreiss Audit-Log',
    deletion_method: 'Sichere Löschung nach Fristablauf',
  },
];
