const fs = require('fs');
let content = fs.readFileSync('src/lib/db/initial-data.ts', 'utf8');

// French indicators - words/sentences that are clearly French
const frenchIndicators = [
  /\bconçue?\b/i, /\bréalisé\b/i, /\bfonctionne\b/i, /\bpermet\b/i,
  /\bpossède\b/i, /\bégalement\b/i, /\bcaractéristique\b/i, /\bavantage\b/i,
  /\bqualité\b/i, /\bprofessionnel\b/i, /\bentreprises?\b/i, /\bbureau\b/i,
  /\butilisateur\b/i, /\butilisation\b/i, /\bidéal\b/i,
  /\bnotre\b/i, /\bvotre\b/i, /\bcelui\b/i, /\bcelle\b/i,
  /\bceux\b/i, /\bcelles\b/i, /\baussi\b/i, /\bainsi\b/i,
  /\bdonc\b/i, /\bcar\b/i, /\bmais\b/i, /\bsi\b/i, /\balors\b/i,
  /\btrès\b/i, /\btout\b/i, /\btous\b/i, /\btoute\b/i, /\btoutes\b/i,
  /\bavec\b/i, /\bsans\b/i, /\bpour\b/i, /\bdans\b/i, /\bsur\b/i,
  /\bqui\b/i, /\bque\b/i, /\bquelle\b/i, /\bce\b/i, /\bcette\b/i,
  /\bces\b/i, /\bun\b/i, /\bune\b/i, /\bdes\b/i,
  /\best\b/i, /\bsont\b/i, /\bpeut\b/i, /\bpeuvent\b/i,
  /\boffre\b/i, /\bgrâce\b/i, /\bnotamment\b/i,
  /\bencore\b/i, /\bdéjà\b/i, /\btoujours\b/i,
  /\bnouveau\b/i, /\bnouvelle\b/i, /\bnouveaux\b/i,
  /\bpremier\b/i, /\bpremière\b/i,
  /\bgrand\b/i, /\bgrande\b/i, /\bpetit\b/i, /\bpetite\b/i,
  /\blong\b/i, /\blongue\b/i, /\blarge\b/i,
  /\bhaut\b/i, /\bhaute\b/i, /\bbas\b/i, /\bbasse\b/i,
  /\brapide\b/i, /\bfacile\b/i, /\bsimple\b/i,
  /\bpuissant\b/i, /\bpuissante\b/i, /\bpuissance\b/i,
  /\befficace\b/i, /\bfiable\b/i, /\brobuste\b/i, /\bsolide\b/i,
  /\bléger\b/i, /\blégère\b/i, /\blourd\b/i, /\blourde\b/i,
  /\bcompact\b/i, /\bcompacte\b/i, /\bmoderne\b/i,
  /\bélégant\b/i, /\bélégante\b/i, /\bdesign\b/i,
  /\bergonomique\b/i, /\bpratique\b/i, /\butile\b/i,
  /\bconfortable\b/i, /\bsilencieux\b/i, /\bsilencieuse\b/i,
  /\béconome\b/i, /\bécologique\b/i,
  /\bintérieur\b/i, /\bextérieur\b/i, /\bmaison\b/i, /\bdomicile\b/i,
  /\bdomotique\b/i, /\bconnecté\b/i, /\bconnectée\b/i,
  /\bintelligent\b/i, /\bintelligente\b/i,
  /\bautomatique\b/i, /\bmanuel\b/i, /\bmanuelle\b/i,
  /\bnumérique\b/i, /\banalogique\b/i,
  /\bécran\b/i, /\baffichage\b/i, /\bmémoire\b/i, /\bstockage\b/i,
  /\bvitesse\b/i, /\bperformance\b/i, /\bperformance\b/i,
  /\bbatterie\b/i, /\bautonomie\b/i, /\bcharge\b/i, /\brecharge\b/i,
  /\bconnexion\b/i, /\bconnectivité\b/i,
  /\bapplication\b/i, /\blogiciel\b/i, /\bmatériel\b/i,
  /\bcompatibilité\b/i, /\bcompatible\b/i,
  /\bgarantie\b/i, /\bservice\b/i, /\blivraison\b/i, /\bexpédition\b/i,
  /\bgratuit\b/i, /\bgratuite\b/i, /\bpayant\b/i,
  /\binclus\b/i, /\bsupplémentaire\b/i, /\boptionnel\b/i,
  /\bstandard\b/i, /\borigine\b/i, /\boriginal\b/i, /\bauthentique\b/i,
  /\bmarque\b/i, /\bmodèle\b/i, /\bgamme\b/i, /\bsérie\b/i,
  /\btype\b/i, /\bdimension\b/i, /\bdimensions\b/i,
  /\bpoids\b/i, /\bcouleur\b/i, /\bcouleurs\b/i,
  /\bformat\b/i, /\btaille\b/i, /\bcapacité\b/i,
  /\brendement\b/i, /\bpages\b/i,
  /\bimpression\b/i, /\bimprimante\b/i, /\bscanner\b/i,
  /\bnumérisation\b/i, /\bcopie\b/i, /\btélécopie\b/i,
  /\btoner\b/i, /\bcartouche\b/i, /\bencre\b/i, /\bpapier\b/i,
  /\brésolution\b/i, /\brecto\b/i, /\bverso\b/i,
  /\bréseau\b/i, /\bentraînement\b/i,
  /\bconception\b/i, /\bfabrication\b/i, /\btechnologie\b/i,
  /\binnovation\b/i, /\bdéveloppement\b/i, /\bexpertise\b/i,
  /\bpremium\b/i, /\bluxe\b/i, /\bexclusif\b/i,
  /\bcertification\b/i, /\bsécurité\b/i, /\bprotection\b/i,
  /\bconsommateur\b/i, /\bclient\b/i, /\bclients\b/i,
  /\bsatisfaction\b/i, /\bsupport\b/i, /\bguide\b/i,
  /\bretour\b/i, /\bremboursement\b/i, /\béchange\b/i,
  /\bcolis\b/i, /\bemballage\b/i, /\bcoût\b/i, /\bprix\b/i,
  /\btarif\b/i, /\bpromotion\b/i, /\bremise\b/i, /\bréduction\b/i,
  /\bvaleur\b/i, /\bdurée\b/i, /\brobustesse\b/i,
  /\brésistance\b/i, /\bfiabilité\b/i, /\bentretien\b/i,
  /\bmaintenance\b/i, /\bréparation\b/i, /\bpièce\b/i, /\bpièces\b/i,
  /\brechange\b/i, /\baccessoire\b/i, /\baccessoires\b/i,
  /\boption\b/i, /\bréglage\b/i, /\bréglages\b/i,
  /\bparamètre\b/i, /\bparamètres\b/i, /\bniveau\b/i, /\bniveaux\b/i,
  /\bintensité\b/i, /\blongueur\b/i, /\blargeur\b/i, /\bhauteur\b/i,
  /\bprofondeur\b/i, /\bdiamètre\b/i, /\btempérature\b/i,
  /\bthermomètre\b/i, /\bprogramme\b/i, /\bprogrammes\b/i,
  /\bvolume\b/i, /\bcontenance\b/i, /\bwatt\b/i, /\bvolt\b/i,
  // More French words
  /\bconçue\b/i, /\bréalisé\b/i, /\bréalisés\b/i,
  /\bfonctionne\b/i, /\bfonctionnel\b/i, /\bfonctionnels\b/i,
  /\bfonction\b/i, /\bfonctions\b/i, /\bfonctionnalité\b/i, /\bfonctionnalités\b/i,
  /\bpermet\b/i, /\bpermettent\b/i,
  /\bpossède\b/i, /\bpossèdent\b/i,
  /\bcaractéristique\b/i, /\bcaractéristiques\b/i,
  /\bavantage\b/i, /\bavantages\b/i,
  /\bqualité\b/i, /\bhaute qualité\b/i,
  /\bprofessionnel\b/i, /\bprofessionnelle\b/i, /\bprofessionnels\b/i,
  /\bprofessionnelles\b/i,
  /\bentreprise\b/i, /\bentreprises\b/i,
  /\bbureau\b/i, /\bbureaux\b/i,
  /\butilisateur\b/i, /\butilisateurs\b/i,
  /\butilisation\b/i, /\butiliser\b/i,
  /\bidéal\b/i, /\bidéale\b/i,
  /\btrès\b/i, /\btout\b/i, /\btous\b/i, /\btoute\b/i, /\btoutes\b/i,
  /\bavec\b/i, /\bsans\b/i, /\bpour\b/i, /\bdans\b/i, /\bsur\b/i,
  /\bce\b/i, /\bcette\b/i, /\bces\b/i,
  /\bson\b/i, /\bsa\b/i, /\bses\b/i,
  /\best\b/i, /\bsont\b/i,
  /\bpeut\b/i, /\bpeuvent\b/i,
  /\boffre\b/i, /\boffrent\b/i,
  /\bgrâce\b/i, /\bnotamment\b/i,
  /\bmais\b/i, /\bou\b/i, /\bni\b/i,
  /\bsi\b/i, /\balors\b/i,
  /\bdonc\b/i, /\bcar\b/i,
  /\bencore\b/i, /\bdéjà\b/i, /\btoujours\b/i, /\bjamais\b/i,
  /\bnouveau\b/i, /\bnouvelle\b/i, /\bnouveaux\b/i, /\bnouvelles\b/i,
  /\bpremier\b/i, /\bpremière\b/i,
  /\bgrand\b/i, /\bgrande\b/i, /\bgrands\b/i, /\bgrandes\b/i,
  /\bpetit\b/i, /\bpetite\b/i, /\bpetits\b/i, /\bpetites\b/i,
  /\blong\b/i, /\blongue\b/i, /\blongs\b/i, /\blongues\b/i,
  /\blarge\b/i, /\bétroit\b/i,
  /\bhaut\b/i, /\bhaute\b/i, /\bhauts\b/i, /\bhautes\b/i,
  /\bbas\b/i, /\bbasse\b/i,
  /\brapide\b/i, /\brapides\b/i,
  /\blent\b/i, /\blente\b/i,
  /\bfacile\b/i, /\bfaciles\b/i,
  /\bdifficile\b/i,
  /\bpuissant\b/i, /\bpuissante\b/i, /\bpuissance\b/i,
  /\befficace\b/i, /\befficacité\b/i,
  /\bfiable\b/i, /\bfiabilité\b/i,
  /\brobuste\b/i, /\bsolide\b/i,
  /\bléger\b/i, /\blégère\b/i,
  /\blourd\b/i, /\blourde\b/i,
  /\bcompact\b/i, /\bcompacte\b/i,
  /\bmoderne\b/i,
  /\bélégant\b/i, /\bélégante\b/i,
  /\bdesign\b/i,
  /\bergonomique\b/i, /\bpratique\b/i, /\butile\b/i,
  /\bconfortable\b/i,
  /\bsilencieux\b/i, /\bsilencieuse\b/i,
  /\béconome\b/i, /\béconomique\b/i, /\bécologique\b/i,
  /\bintérieur\b/i, /\bextérieur\b/i,
  /\bmaison\b/i, /\bdomicile\b/i,
  /\bdomotique\b/i,
  /\bconnecté\b/i, /\bconnectée\b/i, /\bconnectés\b/i,
  /\bintelligent\b/i, /\bintelligente\b/i,
  /\bautomatique\b/i,
  /\bmanuel\b/i, /\bmanuelle\b/i,
  /\bdigital\b/i, /\bnumérique\b/i, /\banalogique\b/i,
  /\bécran\b/i, /\bécran tactile\b/i, /\baffichage\b/i,
  /\bmémoire\b/i, /\bstockage\b/i,
  /\bvitesse\b/i,
  /\bpuissance\b/i, /\bperformance\b/i,
  /\bbatterie\b/i, /\bautonomie\b/i, /\bcharge\b/i, /\brecharge\b/i,
  /\bconnexion\b/i, /\bconnectivité\b/i,
  /\bapplication\b/i, /\blogiciel\b/i, /\bmatériel\b/i,
  /\bcompatibilité\b/i, /\bcompatible\b/i,
  /\bgarantie\b/i, /\bservice après-vente\b/i,
  /\blivraison\b/i, /\bexpédition\b/i,
  /\bgratuit\b/i, /\bgratuite\b/i,
  /\binclus\b/i, /\bsupplémentaire\b/i, /\boptionnel\b/i,
  /\bstandard\b/i, /\boriginal\b/i, /\bauthentique\b/i,
  /\bmarque\b/i, /\bmodèle\b/i, /\bgamme\b/i, /\bsérie\b/i,
  /\bdimension\b/i, /\bdimensions\b/i,
  /\bpoids\b/i, /\bcouleur\b/i, /\bcouleurs\b/i,
  /\bformat\b/i, /\btaille\b/i, /\bcapacité\b/i,
  /\brendement\b/i, /\brendements\b/i, /\bpages\b/i,
  /\bimpression\b/i, /\bimprimante\b/i,
  /\bscanner\b/i, /\bnumérisation\b/i,
  /\bcopie\b/i, /\bcopier\b/i, /\btélécopie\b/i,
  /\btoner\b/i, /\bcartouche\b/i, /\bencre\b/i, /\bpapier\b/i,
  /\brésolution\b/i,
  /\brecto verso\b/i, /\brecto-verso\b/i,
  /\bréseau\b/i,
  /\bcasque\b/i, /\bécouteurs\b/i, /\benceinte\b/i, /\bmicrophone\b/i,
  /\bcaméra\b/i, /\bappareil photo\b/i,
  /\bvidéo\b/i, /\baudio\b/i, /\bmusique\b/i, /\bson\b/i,
  /\bvolume\b/i,
  /\btactile\b/i,
  /\bconception\b/i, /\bfabrication\b/i, /\bproduction\b/i,
  /\btechnologie\b/i, /\binnovation\b/i, /\brecherche\b/i,
  /\bdéveloppement\b/i, /\bexpertise\b/i, /\bsavoir-faire\b/i,
  /\btradition\b/i, /\bhistoire\b/i, /\bhéritage\b/i,
  /\bpremium\b/i, /\bluxe\b/i,
  /\bhaut de gamme\b/i, /\bentrée de gamme\b/i, /\bmilieu de gamme\b/i,
  /\bexclusif\b/i, /\bexclusive\b/i,
  /\blimité\b/i, /\blimitée\b/i,
  /\bspécial\b/i, /\bspéciale\b/i,
  /\bédition\b/i, /\bcollection\b/i,
  /\blabel\b/i, /\bcertification\b/i, /\bnorme\b/i, /\bnormes\b/i,
  /\bconformité\b/i, /\bsécurité\b/i, /\bprotection\b/i,
  /\bprivacy\b/i, /\bconfidentialité\b/i,
  /\bconsommateur\b/i, /\bconsommateurs\b/i,
  /\bclient\b/i, /\bclients\b/i,
  /\bfidélité\b/i, /\bsatisfaction\b/i,
  /\bservice\b/i, /\bsupport\b/i, /\baide\b/i,
  /\bdocumentation\b/i, /\bmanuel\b/i, /\bguide\b/i, /\btutoriel\b/i,
  /\bcontact\b/i, /\bréclamation\b/i,
  /\bretour\b/i, /\bremboursement\b/i, /\béchange\b/i,
  /\blivraison\b/i, /\bexpédition\b/i, /\bsuivi\b/i,
  /\bcolis\b/i, /\bemballage\b/i,
  /\bcoût\b/i, /\bcoûts\b/i, /\bprix\b/i, /\btarif\b/i,
  /\bpromotion\b/i, /\bpromotions\b/i,
  /\bremise\b/i, /\bréduction\b/i,
  /\bbon\b/i, /\bbons\b/i, /\boffre\b/i, /\boffres\b/i,
  /\bvaleur\b/i, /\brapport qualité-prix\b/i,
  /\binvestissement\b/i, /\béconomies\b/i,
  /\blongue durée\b/i, /\bdurée de vie\b/i,
  /\brobustesse\b/i, /\brésistance\b/i, /\bsolidité\b/i,
  /\bfiabilité\b/i, /\bpérennité\b/i,
  /\bentretien\b/i, /\bnettoyage\b/i, /\bmaintenance\b/i,
  /\bréparation\b/i, /\bpièce\b/i, /\bpièces\b/i, /\brechange\b/i,
  /\baccessoire\b/i, /\baccessoires\b/i,
  /\boption\b/i, /\boptions\b/i,
  /\bpersonnalisation\b/i,
  /\bréglage\b/i, /\bréglages\b/i,
  /\bparamètre\b/i, /\bparamètres\b/i,
  /\bmode\b/i, /\bmodes\b/i,
  /\bprogramme\b/i, /\bprogrammes\b/i,
  /\bniveau\b/i, /\bniveaux\b/i,
  /\bintensité\b/i, /\bdébit\b/i,
  /\bcapacité\b/i, /\bvolume\b/i, /\btaille\b/i, /\bformat\b/i,
  /\bpoids\b/i, /\bdimension\b/i, /\bdimensions\b/i,
  /\blongueur\b/i, /\blargeur\b/i, /\bhauteur\b/i, /\bprofondeur\b/i,
  /\bdiamètre\b/i, /\bépaisseur\b/i, /\bsurface\b/i, /\bcontenance\b/i,
  /\bpuissance\b/i, /\bwatt\b/i, /\bwatts\b/i, /\bvolt\b/i, /\bampère\b/i,
  /\bfréquence\b/i, /\bhertz\b/i, /\bdecibel\b/i,
  /\blumens\b/i, /\blux\b/i, /\bkelvin\b/i, /\bcelsius\b/i, /\bfahrenheit\b/i,
  /\bwatt-heure\b/i, /\bpascal\b/i, /\bnewton\b/i,
  // French articles and pronouns
  /\bj'\b/i, /\bt'\b/i, /\bm'\b/i, /\bs'\b/i, /\bn'\b/i,
  /\bl'\b/i, /\bd'\b/i, /\bqu'\b/i, /\bc'\b/i,
  /\bje\b/i, /\btu\b/i, /\bil\b/i, /\belle\b/i, /\bnous\b/i, /\bvous\b/i,
  /\bme\b/i, /\bte\b/i, /\blui\b/i, /\bnous\b/i, /\bvous\b/i, /\bleur\b/i,
  /\blo\b/i, /\bla\b/i, /\bles\b/i,
  /\bdu\b/i, /\bau\b/i, /\baux\b/i,
  /\ben\b/i, /\bpar\b/i, /\bpour\b/i, /\bsans\b/i, /\bsur\b/i,
  /\bsous\b/i, /\bentre\b/i, /\bvers\b/i, /\bchez\b/i,
  /\bdepuis\b/i, /\bpendant\b/i, /\bavant\b/i, /\baprès\b/i,
  /\bselon\b/i, /\bcontre\b/i,
  /\bquelque\b/i, /\bplusieurs\b/i, /\bchaque\b/i,
  /\bmême\b/i, /\bautre\b/i, /\bautres\b/i,
  /\btel\b/i, /\btelle\b/i, /\btels\b/i,
  /\baussi\b/i, /\btrop\b/i, /\bmoins\b/i, /\bpeu\b/i, /\bbeaucoup\b/i,
  /\bbien\b/i, /\bmal\b/i,
  /\bvite\b/i, /\blentement\b/i,
  /\bsouvent\b/i, /\bparfois\b/i,
  /\brien\b/i, /\bquelque\b/i,
  /\bici\b/i, /\blà\b/i, /\boù\b/i,
  /\bcomment\b/i, /\bpourquoi\b/i,
  /\bquel\b/i, /\bquelle\b/i, /\bquels\b/i,
  /\bquelques\b/i, /\bcertains\b/i,
  /\bbon\b/i, /\bmauvais\b/i, /\bmeilleur\b/i, /\bpire\b/i,
  /\bjeune\b/i, /\briche\b/i, /\bpauvre\b/i,
  /\bfort\b/i, /\bfaible\b/i,
  /\bchaud\b/i, /\bsec\b/i, /\bmouillé\b/i,
  /\bpropre\b/i, /\bsale\b/i,
  /\bcalm\b/i, /\bbruyant\b/i,
  /\bdur\b/i, /\bdoux\b/i,
  /\bépais\b/i, /\bmince\b/i,
  /\bplein\b/i, /\bvide\b/i,
  /\bouvert\b/i, /\bfermé\b/i,
  /\bensemble\b/i, /\bseul\b/i,
  /\blibre\b/i, /\boccupé\b/i,
  /\bsûr\b/i, /\bdangereux\b/i,
  /\bpossible\b/i, /\bimpossible\b/i,
  /\bnécessaire\b/i,
  /\bimportant\b/i, /\bintéressant\b/i,
  /\bamusant\b/i, /\bennuyeux\b/i,
  /\bbizarre\b/i, /\bétrange\b/i,
  /\bcontent\b/i, /\bmécontent\b/i,
  /\bfatigué\b/i, /\bheureux\b/i, /\btriste\b/i,
  /\bsérieux\b/i, /\bdrôle\b/i,
  /\bgentil\b/i, /\bméchant\b/i,
  /\bpoli\b/i, /\bimpoli\b/i,
  /\bstupid\b/i,
  /\bvrai\b/i, /\bfaux\b/i,
  /\bjuste\b/i,
  /\bsuivant\b/i, /\bprécédent\b/i,
  /\bunique\b/i,
  /\bentier\b/i, /\bpartiel\b/i,
  /\bcomplet\b/i, /\bincomplet\b/i,
  /\bprêt\b/i,
  /\bnormal\b/i, /\bspécial\b/i, /\bparticulier\b/i,
  /\bgénéral\b/i, /\bprivé\b/i, /\bpublic\b/i, /\bcommun\b/i,
  /\bpropre\b/i,
  /\bdouble\b/i, /\bmultiple\b/i,
  /\btotal\b/i,
  /\bglobal\b/i, /\blocal\b/i,
  /\bnational\b/i, /\binternational\b/i,
  /\bmondial\b/i, /\brégional\b/i,
  /\burbain\b/i, /\brural\b/i,
  /\bancien\b/i, /\brécent\b/i, /\bactuel\b/i,
  /\bfutur\b/i, /\bpassé\b/i,
  /\bpresent\b/i, /\bpermanent\b/i, /\btemporaire\b/i, /\bdéfinitif\b/i,
  /\bcontinu\b/i, /\bintermittent\b/i,
  /\brégulier\b/i, /\birrégulier\b/i,
  /\bfrequent\b/i, /\brare\b/i,
  /\bcommun\b/i, /\bexceptionnel\b/i,
  /\bordinaire\b/i, /\bextraordinaire\b/i,
  /\bnaturel\b/i, /\bartificiel\b/i,
  /\bréel\b/i, /\bimaginaire\b/i,
  /\bphysique\b/i, /\bmoral\b/i,
  /\bintellectuel\b/i, /\bspirituel\b/i,
  /\bémotionnel\b/i, /\bsentimental\b/i,
  /\bthéorique\b/i,
  /\bconcret\b/i, /\babstrait\b/i,
  /\bpositif\b/i, /\bnégatif\b/i,
  /\boptimiste\b/i, /\bpessimiste\b/i,
  /\bdynamique\b/i, /\bstatique\b/i,
  /\bmobile\b/i, /\bfixe\b/i,
  /\bstable\b/i, /\binstable\b/i,
  /\bprudent\b/i, /\bbaudacieux\b/i, /\bcourageux\b/i,
  /\btimide\b/i,
];

function isFrenchSentence(sentence) {
  const trimmed = sentence.trim();
  if (trimmed.length < 5) return false;
  
  // Check if sentence contains any French indicator
  for (const indicator of frenchIndicators) {
    if (indicator.test(trimmed)) {
      return true;
    }
  }
  return false;
}

function processDescription(text) {
  if (!text || text.length < 20) return text;
  
  // Split into sentences (by . ! ? or newlines)
  const sentences = text.split(/(?<=[.!?])\s+|\n+/);
  
  // Keep only non-French sentences
  const kept = sentences.filter(s => !isFrenchSentence(s));
  
  if (kept.length === 0) return text; // Keep original if nothing to remove
  return kept.join(' ');
}

// Process all descriptions
let descFixed = 0;
let shortFixed = 0;

content = content.replace(/"description": "([^"]+)"/g, (match, desc) => {
  const newDesc = processDescription(desc);
  if (newDesc !== desc) {
    descFixed++;
    return '"description": "' + newDesc + '"';
  }
  return match;
});

content = content.replace(/"short_description": "([^"]+)"/g, (match, short) => {
  const newShort = processDescription(short);
  if (newShort !== short) {
    shortFixed++;
    return '"short_description": "' + newShort + '"';
  }
  return match;
});

fs.writeFileSync('src/lib/db/initial-data.ts', content);
console.log('Descriptions longues nettoyées:', descFixed);
console.log('Descriptions courtes nettoyées:', shortFixed);

// Verify
const verify = fs.readFileSync('src/lib/db/initial-data.ts', 'utf8');
const remaining = verify.match(/"description": "[^"]*[àâäéèêëïîôùûüÿçœæ][^"]*"/g);
console.log('Descriptions avec caractères français restants:', remaining ? remaining.length : 0);
