const fs = require('fs');
let content = fs.readFileSync('src/lib/db/initial-data.ts', 'utf8');

const replacements = [
  ['qualité', 'Qualität'], ['votre', 'Ihre'], ['fonctionne', 'funktioniert'],
  ['permet', 'ermöglicht'], ['également', 'ebenfalls'], ['conçue', 'entwickelt'],
  ['avantage', 'Vorteil'], ['professionnel', 'professionell'], ['notre', 'unser'],
  ['réalisé', 'hergestellt'], ['caractéristique', 'Merkmal'],
  ['caractéristiques', 'Merkmale'], ['avantages', 'Vorteile'],
  ['fonctionnel', 'funktional'], ['possède', 'verfügt'],
  ['entreprises', 'Unternehmen'], ['entreprise', 'Unternehmen'],
  ['utilisateur', 'Benutzer'], ['utilisateurs', 'Benutzer'],
  ['utilisation', 'Verwendung'], ['idéal', 'ideal'], ['idéale', 'ideal'],
  ['bureau', 'Büro'], ['bureaux', 'Büros'], ['très', 'sehr'],
  ['tout', 'alles'], ['tous', 'alle'], ['toute', 'alle'], ['toutes', 'alle'],
  ['avec', 'mit'], ['sans', 'ohne'], ['pour', 'für'], ['dans', 'in'], ['sur', 'auf'],
  ['ce', 'dies'], ['cette', 'diese'], ['ces', 'diese'],
  ['son', 'sein'], ['sa', 'ihre'], ['ses', 'ihre'],
  ['est', 'ist'], ['sont', 'sind'], ['peut', 'kann'], ['peuvent', 'können'],
  ['offre', 'bietet'], ['offrent', 'bieten'], ['grâce', 'dank'],
  ['notamment', 'insbesondere'], ['mais', 'aber'], ['ou', 'oder'],
  ['si', 'wenn'], ['alors', 'dann'], ['donc', 'daher'], ['car', 'denn'],
  ['encore', 'noch'], ['déjà', 'bereits'], ['toujours', 'immer'],
  ['nouveau', 'neu'], ['nouvelle', 'neue'], ['nouveaux', 'neue'],
  ['premier', 'erste'], ['première', 'erste'],
  ['grand', 'groß'], ['grande', 'große'], ['petit', 'klein'], ['petite', 'kleine'],
  ['long', 'lang'], ['longue', 'lange'], ['large', 'breit'],
  ['haut', 'hoch'], ['haute', 'hohe'],
  ['rapide', 'schnell'], ['rapides', 'schnell'],
  ['facile', 'einfach'], ['simple', 'einfach'],
  ['puissant', 'leistungsstark'], ['puissante', 'leistungsstark'], ['puissance', 'Leistung'],
  ['efficace', 'wirksam'], ['fiable', 'zuverlässig'],
  ['robuste', 'robust'], ['solide', 'robust'],
  ['léger', 'leicht'], ['légère', 'leichte'],
  ['compact', 'kompakt'], ['compacte', 'kompakt'],
  ['moderne', 'modern'], ['élégant', 'elegant'], ['élégante', 'elegante'],
  ['ergonomique', 'ergonomisch'], ['pratique', 'praktisch'],
  ['confortable', 'bequem'], ['silencieux', 'leise'], ['silencieuse', 'leise'],
  ['économe', 'sparsam'], ['intérieur', 'Innenraum'], ['extérieur', 'Außenbereich'],
  ['maison', 'Zuhause'], ['domotique', 'Smart Home'],
  ['connecté', 'verbunden'], ['connectée', 'verbunden'],
  ['intelligent', 'intelligent'], ['intelligente', 'intelligente'],
  ['automatique', 'automatisch'], ['manuel', 'manuell'], ['manuelle', 'manuell'],
  ['écran tactile', 'Touchscreen'], ['écran', 'Bildschirm'],
  ['affichage', 'Anzeige'], ['mémoire', 'Speicher'], ['stockage', 'Speicher'],
  ['vitesse', 'Geschwindigkeit'], ['performance', 'Leistung'],
  ['batterie', 'Akku'], ['autonomie', 'Akkulaufzeit'],
  ['connexion', 'Verbindung'], ['connectivité', 'Konnektivité'],
  ['wifi', 'WLAN'], ['sans fil', 'kabellos'], ['filaire', 'verkabelt'],
  ['application', 'App'], ['logiciel', 'Software'], ['matériel', 'Hardware'],
  ['compatibilité', 'Kompatibilität'], ['compatible', 'kompatibel'],
  ['garantie', 'Garantie'], ['livraison', 'Lieferung'], ['expédition', 'Versand'],
  ['gratuit', 'kostenlos'], ['gratuite', 'kostenlos'],
  ['inclus', 'inklusive'], ['supplémentaire', 'zusätzlich'],
  ['standard', 'Standard'], ['original', 'Original'], ['authentique', 'authentisch'],
  ['marque', 'Marke'], ['modèle', 'Modell'], ['gamme', 'Reihe'], ['série', 'Serie'],
  ['dimensions', 'Abmessungen'], ['dimension', 'Abmessung'],
  ['poids', 'Gewicht'], ['couleur', 'Farbe'],
  ['noir', 'Schwarz'], ['blanc', 'Weiß'], ['gris', 'Grau'],
  ['format', 'Format'], ['taille', 'Größe'], ['capacité', 'Kapazität'],
  ['rendement', 'Ertrag'], ['pages', 'Seiten'],
  ['impression', 'Drucken'], ['imprimante', 'Drucker'],
  ['numérisation', 'Scannen'], ['copie', 'Kopie'], ['télécopie', 'Fax'],
  ['cartouche', 'Patrone'], ['encre', 'Tinte'], ['papier', 'Papier'],
  ['résolution', 'Auflösung'], ['recto-verso', 'doppelseitig'],
  ['recto verso', 'doppelseitig'], ['réseau', 'Netzwerk'],
  ['tactile', 'berührungsempfindlich'],
  ['aspirateur', 'Staubsauger'], ['aspirateurs', 'Staubsauger'],
  ['aspiration', 'Saugkraft'], ['nettoyage', 'Reinigung'],
  ['robot', 'Roboter'], ['autonome', 'autonom'],
  ['navigation', 'Navigation'], ['barbecue', 'Grill'],
  ['électrique', 'elektrisch'], ['cuisson', 'Garen'],
  ['congélateur', 'Gefrierschrank'], ['réfrigérateur', 'Kühlschrank'],
  ['froid', 'Kälte'], ['cuisinière', 'Herd'], ['four', 'Ofen'],
  ['micro-ondes', 'Mikrowelle'], ['hotte', 'Dunstabzugshaube'],
  ['plaque', 'Kochfeld'], ['induction', 'Induktion'], ['céramique', 'Keramik'],
  ['fritteuse', 'Friteuse'], ['huile', 'Öl'], ['aliments', 'Lebensmittel'],
  ['croustillant', 'knusprig'], ['lave-linge', 'Waschmaschine'],
  ['séchage', 'Trocknen'], ['sèche-linge', 'Wäschetrockner'],
  ['énergie', 'Energie'], ['montre connectée', 'Smartwatch'], ['montre', 'Uhr'],
  ['fitness', 'Fitness'], ['calories', 'Kalorien'],
  ['fréquence cardiaque', 'Herzfrequenz'], ['pouls', 'Puls'],
  ['étanche', 'wasserdicht'], ['home trainer', 'Heimtrainer'],
  ['tapis de course', 'Laufband'], ['elliptique', 'Crosstrainer'],
  ['musculation', 'Krafttraining'], ['haltères', 'Hanteln'],
  ['rowing', 'Rudern'], ['cardio', 'Cardio'], ['fréquence', 'Frequenz'],
  ['pente', 'Neigung'], ['inclinable', 'verstellbar'],
  ['surface de course', 'Lauffläche'], ['moteur', 'Motor'],
  ['pliable', 'faltbar'], ['roues de transport', 'Transportrollen'],
  ['amortissement', 'Dämpfung'], ['entraînement', 'Training'],
  ['conception', 'Konstruktion'], ['fabrication', 'Herstellung'],
  ['technologie', 'Technologie'], ['innovation', 'Innovation'],
  ['développement', 'Entwicklung'], ['expertise', 'Expertise'],
  ['premium', 'Premium'], ['luxe', 'Luxus'],
  ['haut de gamme', 'High-End'], ['exclusif', 'exklusiv'],
  ['certification', 'Zertifizierung'], ['sécurité', 'Sicherheit'],
  ['protection', 'Schutz'], ['consommateur', 'Verbraucher'],
  ['client', 'Kunde'], ['clients', 'Kunden'],
  ['satisfaction', 'Zufriedenheit'], ['support', 'Support'],
  ['guide', 'Leitfaden'], ['retour', 'Rückgabe'],
  ['remboursement', 'Erstattung'], ['échange', 'Umtausch'],
  ['colis', 'Paket'], ['emballage', 'Verpackung'],
  ['coût', 'Kosten'], ['prix', 'Preis'], ['tarif', 'Tarif'],
  ['promotion', 'Aktion'], ['remise', 'Rabatt'], ['réduction', 'Rabatt'],
  ['valeur', 'Wert'], ['durée de vie', 'Lebensdauer'],
  ['robustesse', 'Robustheit'], ['résistance', 'Widerstand'],
  ['fiabilité', 'Zuverlässigkeit'], ['entretien', 'Pflege'],
  ['maintenance', 'Wartung'], ['réparation', 'Reparatur'],
  ['pièce', 'Teil'], ['pièces', 'Teile'], ['rechange', 'Ersatz'],
  ['accessoire', 'Zubehör'], ['accessoires', 'Zubehör'],
  ['option', 'Option'], ['réglage', 'Einstellung'], ['réglages', 'Einstellungen'],
  ['paramètre', 'Parameter'], ['paramètres', 'Parameter'],
  ['niveau', 'Stufe'], ['niveaux', 'Stufen'], ['intensité', 'Intensität'],
  ['longueur', 'Länge'], ['largeur', 'Breite'], ['hauteur', 'Höhe'],
  ['profondeur', 'Tiefe'], ['diamètre', 'Durchmesser'],
  ['température', 'Temperatur'], ['thermomètre', 'Thermometer'],
  ['programme', 'Programm'], ['programmes', 'Programme'],
  ['volume', 'Volumen'], ['contenance', 'Fassungsvermögen'],
  ['watt', 'Watt'], ['volt', 'Volt'],
  // French articles/prepositions not yet covered
  ['l\'', 'das '], ['d\'', 'von '], ['n\'', 'nicht '], ['j\'', 'ich '],
  ['s\'', 'sich '], ['m\'', 'mich '], ['t\'', 'dich '], ['qu\'', 'dass '],
  ['c\'', 'es '], ['quelque', 'einige'], ['plusieurs', 'mehrere'],
  ['chaque', 'jede'], ['toute', 'alle'], ['tous', 'alle'],
  ['même', 'sowie'], ['autre', 'andere'], ['autres', 'andere'],
  ['tel', 'solcher'], ['telle', 'solche'], ['tels', 'solche'],
  ['tellement', 'so'], ['aussi', 'auch'], ['trop', 'zu'],
  ['moins', 'weniger'], ['peu', 'wenig'], ['beaucoup', 'viel'],
  ['trop', 'zu'], ['moins', 'weniger'], ['entre', 'zwischen'],
  ['vers', 'nach'], ['depuis', 'seit'], ['pendant', 'während'],
  ['avant', 'vor'], ['après', 'nach'], ['selon', 'gemäß'],
  ['contre', 'gegen'], ['par', 'von'], ['chez', 'bei'],
  ['sous', 'unter'], ['derrière', 'hinter'], ['devant', 'vor'],
  ['près', 'in der Nähe'], ['loin', 'weit'],
  ['là', 'dort'], ['ici', 'hier'], ['où', 'wo'],
  ['comment', 'wie'], ['pourquoi', 'warum'],
  ['quel', 'welcher'], ['quelle', 'welche'], ['quels', 'welche'],
  ['quelques', 'einige'], ['certains', 'einige'],
  ['beaucoup', 'viele'], ['peu', 'wenige'],
  ['rien', 'nichts'], ['quelque', 'etwas'],
  ['aussi', 'auch'], ['très', 'sehr'], ['trop', 'zu'],
  ['moins', 'weniger'], ['peu', 'wenig'],
  ['bien', 'gut'], ['mal', 'schlecht'],
  ['vite', 'schnell'], ['lentement', 'langsam'],
  ['souvent', 'oft'], ['parfois', 'manchmal'],
  ['jamais', 'nie'], ['toujours', 'immer'],
  ['encore', 'noch'], ['déjà', 'bereits'],
  ['ici', 'hier'], ['là', 'dort'],
  ['maintenant', 'jetzt'], ['hier', 'gestern'],
  ['demain', 'morgen'], ['aujourd\'hui', 'heute'],
  ['bon', 'gut'], ['mauvais', 'schlecht'],
  ['meilleur', 'besser'], ['pire', 'schlechter'],
  ['grand', 'groß'], ['petit', 'klein'],
  ['haut', 'hoch'], ['bas', 'niedrig'],
  ['nouveau', 'neu'], ['vieux', 'alt'],
  ['jeune', 'jung'], ['vieux', 'alt'],
  ['riche', 'reich'], ['pauvre', 'arm'],
  ['fort', 'stark'], ['faible', 'schwach'],
  ['chaud', 'heiß'], ['froid', 'kalt'],
  ['sec', 'trocken'], ['mouillé', 'nass'],
  ['propre', 'sauber'], ['sale', 'schmutzig'],
  ['calm', 'ruhig'], ['bruyant', 'laut'],
  ['lourd', 'schwer'], ['léger', 'leicht'],
  ['dur', 'hart'], ['doux', 'weich'],
  ['épais', 'dick'], ['mince', 'dünn'],
  ['plein', 'voll'], ['vide', 'leer'],
  ['ouvert', 'offen'], ['fermé', 'geschlossen'],
  ['ici', 'hier'], ['là-bas', 'dort'],
  ['ensemble', 'zusammen'], ['seul', 'allein'],
  ['libre', 'frei'], ['occupé', 'beschäftigt'],
  ['sûr', 'sicher'], ['dangereux', 'gefährlich'],
  ['facile', 'einfach'], ['difficile', 'schwierig'],
  ['possible', 'möglich'], ['impossible', 'unmöglich'],
  ['nécessaire', 'notwendig'], ['utile', 'nützlich'],
  ['important', 'wichtig'], ['intéressant', 'interessant'],
  ['amusant', 'unterhaltsam'], ['ennuyeux', 'langweilig'],
  ['bizarre', 'seltsam'], ['étrange', 'komisch'],
  ['content', 'zufrieden'], ['mécontent', 'unzufrieden'],
  ['fatigué', 'müde'], ['énerve', 'verärgert'],
  ['heureux', 'glücklich'], ['triste', 'traurig'],
  ['sérieux', 'ernst'], ['drôle', 'lustig'],
  ['gentil', 'nett'], ['méchant', 'böse'],
  ['poli', 'höflich'], ['impoli', 'unhöflich'],
  ['intelligent', 'intelligent'], ['stupid', 'dumm'],
  ['vrai', 'wahr'], ['faux', 'falsch'],
  ['juste', 'richtig'], ['mauvais', 'falsch'],
  ['premier', 'erster'], ['dernier', 'letzter'],
  ['suivant', 'nächster'], ['précédent', 'vorheriger'],
  ['seul', 'einzig'], ['unique', 'einzigartig'],
  ['entier', 'ganz'], ['partiel', 'teilweise'],
  ['complet', 'vollständig'], ['incomplet', 'unvollständig'],
  ['prêt', 'bereit'], ['occupé', 'beschäftigt'],
  ['libre', 'frei'], ['fermé', 'geschlossen'],
  ['ouvert', 'offen'], ['actif', 'aktiv'],
  ['inactif', 'inaktiv'], ['normal', 'normal'],
  ['spécial', 'speziell'], ['particulier', 'besonders'],
  ['général', 'allgemein'], ['privé', 'privé'],
  ['public', 'öffentlich'], ['commun', 'gemeinsam'],
  ['propre', 'eigen'], ['simple', 'einfach'],
  ['double', 'doppel'], ['multiple', 'mehrfach'],
  ['total', 'gesamt'], ['partiel', 'teilweise'],
  ['global', 'global'], ['local', 'lokal'],
  ['national', 'national'], ['international', 'international'],
  ['mondial', 'weltweit'], ['régional', 'regional'],
  ['urbain', 'städtisch'], ['rural', 'ländlich'],
  ['moderne', 'modern'], ['ancien', 'alt'],
  ['récent', 'neu'], ['actuel', 'aktuell'],
  ['futur', 'zukünftig'], ['passé', 'vergangen'],
  ['présent', 'gegenwärtig'], ['permanent', 'dauerhaft'],
  ['temporaire', 'temporär'], ['définitif', 'endgültig'],
  ['continu', 'ständig'], ['intermittent', 'unterbrochen'],
  ['régulier', 'regelmäßig'], ['irrégulier', 'unregelmäßig'],
  ['fréquent', 'häufig'], ['rare', 'selten'],
  ['commun', 'häufig'], ['exceptionnel', 'außergewöhnnel'],
  ['ordinaire', 'gewöhnlich'], ['extraordinaire', 'außergewöhnlich'],
  ['naturel', 'natürlich'], ['artificiel', 'künstlich'],
  ['réel', 'tatsächlich'], ['imaginaire', 'imaginär'],
  ['physique', 'physisch'], ['moral', 'moralisch'],
  ['intellectuel', 'intellektuel'], ['spirituel', 'spirituell'],
  ['émotionnel', 'emotional'], ['sentimental', 'sentimental'],
  ['pratique', 'praktisch'], ['théorique', 'theoretisch'],
  ['concret', 'konkret'], ['abstrait', 'abstrakt'],
  ['positif', 'positiv'], ['négativ', 'negativ'],
  ['optimiste', 'optimistisch'], ['pessimiste', 'pessimistisch'],
  ['actif', 'aktiv'], ['passif', 'passif'],
  ['dynamique', 'dynamisch'], ['statique', 'statisch'],
  ['mobile', 'mobil'], ['fixe', 'fest'],
  ['stable', 'stabil'], ['instable', 'instabil'],
  ['sûr', 'sicher'], ['dangereux', 'gefährlich'],
  ['risqué', 'riskant'], ['prudent', 'vorsichtig'],
  ['audacieux', 'mutig'], ['courageux', 'mutig'],
  ['timide', 'schüchtern'], ['bold', 'frech'],
];

let count = 0;
for (const [fr, de] of replacements) {
  const regex = new RegExp(fr.replace(/[.*+?^${}()|[\]\\]/g, '\\$&'), 'gi');
  const matches = content.match(regex);
  if (matches) {
    content = content.replace(regex, de);
    count += matches.length;
  }
}

fs.writeFileSync('src/lib/db/initial-data.ts', content);
console.log('Remplacements effectués:', count);

// Verify
const verify = fs.readFileSync('src/lib/db/initial-data.ts', 'utf8');
const remainingFrench = verify.match(/[àâäéèêëïîôùûüÿçœæ]/g);
console.log('Caractères français restants:', remainingFrench ? remainingFrench.length : 0);
